spring:
  datasource:
    # jdbc configuration
    url: jdbc:mysql://localhost:3306/testbase?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    # connection pool config
    druid:
      initial-size: 5
      max-active: 5
    # monitor config